# fly.toml app configuration file generated for ocop-backend on 2023-08-02T15:41:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ocop-backend"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
